import 'dart:async';

import 'package:attendify/models/user.dart';
import 'package:attendify/services/auth.dart';
import 'package:attendify/services/databases.dart';
import 'package:firebase_auth/firebase_auth.dart' as fb_auth;
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:google_sign_in/google_sign_in.dart';

// Import the generated mocks (will be generated by build_runner)
// For now, this import will show an error until mocks are generated.
// The user will need to run `flutter pub run build_runner build --delete-conflicting-outputs`
import 'logout_test.mocks.dart';

// Annotations to generate mocks
@GenerateMocks([
  fb_auth.FirebaseAuth,
  fb_auth.UserCredential,
  fb_auth.User,
  GoogleSignIn,
  GoogleSignInAccount,
  GoogleSignInAuthentication,
  DatabaseService,
])
void main() {
  late AuthService authService;
  late MockFirebaseAuth mockFirebaseAuth;
  late MockGoogleSignIn mockGoogleSignIn;
  late MockDatabaseService mockDatabaseService;
  late MockUser mockUser; // This is fb_auth.User
  late MockUserCredential mockUserCredential;
  late MockGoogleSignInAccount mockGoogleSignInAccount;
  late MockGoogleSignInAuthentication mockGoogleSignInAuthentication;

  setUp(() {
    mockFirebaseAuth = MockFirebaseAuth();
    mockGoogleSignIn = MockGoogleSignIn();
    mockDatabaseService = MockDatabaseService();

    // Assumes AuthService has a test constructor or a way to inject mocks
    authService = AuthService.test(mockFirebaseAuth, mockGoogleSignIn, mockDatabaseService);

    mockUser = MockUser();
    mockUserCredential = MockUserCredential();
    mockGoogleSignInAccount = MockGoogleSignInAccount();
    mockGoogleSignInAuthentication = MockGoogleSignInAuthentication();

    // Common stubs for mockUser
    when(mockUser.uid).thenReturn('test_uid');
    when(mockUser.email).thenReturn('test@example.com');
    when(mockUser.displayName).thenReturn('Test User');
    when(mockUser.photoURL).thenReturn('http://example.com/photo.jpg');

    // Common stub for mockUserCredential
    when(mockUserCredential.user).thenReturn(mockUser);
  });

  group('AuthService Tests', () {
    group('signInWithEmailAndPassword', () {
      test('should return UserHandler on successful sign-in', () async {
        when(mockFirebaseAuth.signInWithEmailAndPassword(
          email: 'test@example.com',
          password: 'password123',
        )).thenAnswer((_) async => mockUserCredential);

        final result = await authService.signInWithEmailAndPassword(
            'test@example.com', 'password123');

        expect(result, isA<UserHandler>());
        expect(result?.uid, 'test_uid');
        verify(mockFirebaseAuth.signInWithEmailAndPassword(
            email: 'test@example.com', password: 'password123')).called(1);
      });

      test('should return null if FirebaseAuth throws exception', () async {
        when(mockFirebaseAuth.signInWithEmailAndPassword(
          email: 'test@example.com',
          password: 'wrongpassword',
        )).thenThrow(fb_auth.FirebaseAuthException(code: 'wrong-password'));

        final result = await authService.signInWithEmailAndPassword(
            'test@example.com', 'wrongpassword');

        expect(result, isNull);
      });
    });

    group('signInWithGoogleProvider', () {
      setUp(() {
        when(mockGoogleSignIn.signIn()).thenAnswer((_) async => mockGoogleSignInAccount);
        when(mockGoogleSignInAccount.email).thenReturn('test@hns-re2sd.dz');
        when(mockGoogleSignInAccount.authentication).thenAnswer((_) async => mockGoogleSignInAuthentication);
        when(mockGoogleSignInAuthentication.accessToken).thenReturn('dummy_access_token');
        when(mockGoogleSignInAuthentication.idToken).thenReturn('dummy_id_token');
        when(mockFirebaseAuth.signInWithCredential(any)).thenAnswer((_) async => mockUserCredential);
        when(mockDatabaseService.isUserRegistered(any)).thenAnswer((_) async => true);
      });

      test('should return UserHandler on successful Google Sign-In', () async {
        final result = await authService.signInWithGoogleProvider();
        expect(result, isA<UserHandler>());
        expect(result.uid, 'test_uid');
        verify(mockGoogleSignIn.signOut()).called(1);
        verify(mockDatabaseService.isUserRegistered('test@hns-re2sd.dz')).called(1);
      });

      test('should throw "no-email" if GoogleSignInAccount is null', () async {
        when(mockGoogleSignIn.signIn()).thenAnswer((_) async => null);
        expect(
          () => authService.signInWithGoogleProvider(),
          throwsA(predicate((e) => e is Exception && e.toString() == 'Exception: no-email'))
        );
      });

      test('should throw "not-hns-email" if email is not from @hns-re2sd.dz', () async {
        when(mockGoogleSignInAccount.email).thenReturn('test@otherdomain.com');
        expect(
          () => authService.signInWithGoogleProvider(),
          throwsA(predicate((e) => e is Exception && e.toString() == 'Exception: not-hns-email'))
        );
      });

      test('should throw "not-registered" if user email is not in DatabaseService', () async {
        when(mockDatabaseService.isUserRegistered('test@hns-re2sd.dz')).thenAnswer((_) async => false);
        expect(
          () => authService.signInWithGoogleProvider(),
          throwsA(predicate((e) => e is Exception && e.toString() == 'Exception: not-registered'))
        );
      });
    });

    group('signUpWithGoogleProvider', () {
      setUp(() {
        when(mockGoogleSignIn.signIn()).thenAnswer((_) async => mockGoogleSignInAccount);
        when(mockGoogleSignInAccount.email).thenReturn('test@hns-re2sd.dz');
        when(mockUser.displayName).thenReturn("Google User"); // Specific for these tests
        when(mockUser.photoURL).thenReturn("google_photo_url");

        when(mockGoogleSignInAccount.authentication).thenAnswer((_) async => mockGoogleSignInAuthentication);
        when(mockGoogleSignInAuthentication.accessToken).thenReturn('dummy_access_token');
        when(mockGoogleSignInAuthentication.idToken).thenReturn('dummy_id_token');
        when(mockFirebaseAuth.signInWithCredential(any)).thenAnswer((_) async => mockUserCredential);

        // Default stubs for DatabaseService checks (true means email is pre-registered if needed)
        when(mockDatabaseService.isTeacherEmailRegistered(any)).thenAnswer((_) async => true);
        when(mockDatabaseService.isAdminEmailRegistered(any)).thenAnswer((_) async => true);

        // Stubs for database update methods
        when(mockDatabaseService.updateUserData(
          userName: anyNamed('userName'), userType: anyNamed('userType'),
          usrUid: anyNamed('usrUid'), email: anyNamed('email'), photoURL: anyNamed('photoURL')))
        .thenAnswer((_) async => null);

        when(mockDatabaseService.updateTeacherData(
          userName: anyNamed('userName'), userType: anyNamed('userType'),
          uid: anyNamed('uid'), email: anyNamed('email'), photoURL: anyNamed('photoURL'),
          modules: anyNamed('modules')))
        .thenAnswer((_) async => null);

        when(mockDatabaseService.updateStudentData(
          userName: anyNamed('userName'), userType: anyNamed('userType'),
          uid: anyNamed('uid'), email: anyNamed('email'), photoURL: anyNamed('photoURL'),
          grade: anyNamed('grade'), speciality: anyNamed('speciality')))
        .thenAnswer((_) async => null);

        when(mockDatabaseService.updateModulesWithCriteria(
          grade: anyNamed('grade'), speciality: anyNamed('speciality'),
          studentUID: anyNamed('studentUID'), studentName: anyNamed('studentName')))
        .thenAnswer((_) async => null);
      });

      test('student sign-up should call correct DatabaseService methods', () async {
        final result = await authService.signUpWithGoogleProvider('student', '1CS', 'SIW');
        expect(result, isA<UserHandler>());
        verify(mockDatabaseService.updateUserData(
            userName: 'Google User', userType: 'student', usrUid: 'test_uid',
            email: 'test@example.com', photoURL: 'google_photo_url')).called(1);
        verify(mockDatabaseService.updateStudentData(
            userName: 'Google User', userType: 'student', uid: 'test_uid',
            email: 'test@example.com', photoURL: 'google_photo_url',
            grade: '1CS', speciality: 'SIW')).called(1);
        verify(mockDatabaseService.updateModulesWithCriteria(
            grade: '1CS', speciality: 'SIW', studentUID: 'test_uid', studentName: 'Google User')).called(1);
      });

      test('teacher sign-up should call correct DatabaseService methods', () async {
        await authService.signUpWithGoogleProvider('teacher', null, null);
        verify(mockDatabaseService.updateUserData(
             userName: 'Google User', userType: 'teacher', usrUid: 'test_uid',
             email: 'test@example.com', photoURL: 'google_photo_url')).called(1);
        verify(mockDatabaseService.updateTeacherData(
            userName: 'Google User', userType: 'teacher', uid: 'test_uid',
            email: 'test@example.com', photoURL: 'google_photo_url', modules: null)).called(1);
      });

      test('should throw "not-hns-teacher" if teacher email not pre-registered', () async {
        when(mockDatabaseService.isTeacherEmailRegistered('test@hns-re2sd.dz')).thenAnswer((_) async => false);
        expect(
          () => authService.signUpWithGoogleProvider('teacher', null, null),
          throwsA(predicate((e) => e is Exception && e.toString() == 'Exception: not-hns-teacher'))
        );
      });

      test('should throw "not-hns-admin" if admin email not pre-registered', () async {
        when(mockDatabaseService.isAdminEmailRegistered('test@hns-re2sd.dz')).thenAnswer((_) async => false);
        expect(
          () => authService.signUpWithGoogleProvider('admin', null, null),
          throwsA(predicate((e) => e is Exception && e.toString() == 'Exception: not-hns-admin'))
        );
      });
    });

    group('signUpWithEmailAndPassword', () {
      setUp(() {
        when(mockFirebaseAuth.createUserWithEmailAndPassword(email: 'new@example.com', password: 'password123'))
            .thenAnswer((_) async => mockUserCredential);
        // Default stubs for DatabaseService calls, similar to Google sign-up
        when(mockDatabaseService.updateUserData(userName: anyNamed('userName'), userType: anyNamed('userType'), usrUid: anyNamed('usrUid'), email: anyNamed('email'), photoURL: anyNamed('photoURL'))).thenAnswer((_) async => null);
        when(mockDatabaseService.updateTeacherData(userName: anyNamed('userName'), userType: anyNamed('userType'), uid: anyNamed('uid'), email: anyNamed('email'), photoURL: anyNamed('photoURL'), modules: anyNamed('modules'))).thenAnswer((_) async => null);
        when(mockDatabaseService.updateStudentData(userName: anyNamed('userName'), userType: anyNamed('userType'), uid: anyNamed('uid'), email: anyNamed('email'), photoURL: anyNamed('photoURL'), grade: anyNamed('grade'), speciality: anyNamed('speciality'))).thenAnswer((_) async => null);
        when(mockDatabaseService.updateModulesWithCriteria(grade: anyNamed('grade'), speciality: anyNamed('speciality'), studentUID: anyNamed('studentUID'), studentName: anyNamed('studentName'))).thenAnswer((_) async => null);

        // For email/password, photoURL might be null initially from Firebase user object
        when(mockUser.photoURL).thenReturn(null);
      });

      test('teacher sign-up should call correct methods and return UserHandler', () async {
        final result = await authService.signUpWithEmailAndPassword(
            'Email Teacher', 'new@example.com', 'password123', 'teacher', modules: ['physics']);

        expect(result, isA<UserHandler>());
        expect(result?.uid, 'test_uid');
        verify(mockDatabaseService.updateUserData(userName: 'Email Teacher', userType: 'teacher', usrUid: 'test_uid', email: 'test@example.com', photoURL: '', )).called(1); // photoURL becomes empty string if null
        verify(mockDatabaseService.updateTeacherData(userName: 'Email Teacher', userType: 'teacher', uid: 'test_uid', email: 'test@example.com', photoURL: '', modules: ['physics'])).called(1);
      });

      test('student sign-up should call correct methods and return UserHandler', () async {
        await authService.signUpWithEmailAndPassword(
            'Email Student', 'new@example.com', 'password123', 'student', grade: '2CS', speciality: 'SIT');

        verify(mockDatabaseService.updateStudentData(userName: 'Email Student', userType: 'student', uid: 'test_uid', email: 'test@example.com', photoURL: '', grade: '2CS', speciality: 'SIT')).called(1);
        verify(mockDatabaseService.updateModulesWithCriteria(grade: '2CS', speciality: 'SIT', studentUID: 'test_uid', studentName: 'Email Student')).called(1);
      });

      test('should return null if FirebaseAuth throws exception', () async {
        when(mockFirebaseAuth.createUserWithEmailAndPassword(email: 'new@example.com', password: 'password123'))
            .thenThrow(fb_auth.FirebaseAuthException(code: 'email-already-in-use'));

        final result = await authService.signUpWithEmailAndPassword(
            'Test User', 'new@example.com', 'password123', 'student');
        expect(result, isNull);
      });
    });

    group('logout', () {
      // This test assumes logout will be refactored to not take BuildContext
      // and return Future<void> or Future<bool> for success/failure indication.
      test('should call signOut on FirebaseAuth', () async {
        when(mockFirebaseAuth.signOut()).thenAnswer((_) async {}); // Mock successful sign out

        // The actual test for logout behavior (e.g. returning true/false)
        // will be refined after AuthService.logout() is refactored.
        // For now, just verify signOut is called.
        await authService.logout(null); // Passing null for context, will be removed in refactor

        verify(mockFirebaseAuth.signOut()).called(1);
      });

      test('should complete if signOut throws (error handled internally)', () async {
        when(mockFirebaseAuth.signOut()).thenThrow(fb_auth.FirebaseAuthException(code: 'test-error'));

        // Expect that the call completes without rethrowing the FirebaseAuthException directly
        await expectLater(authService.logout(null), completes);
        verify(mockFirebaseAuth.signOut()).called(1);
      });
    });

    group('currentUser', () {
      test('currentUsr getter should return current FirebaseAuth user', () {
        when(mockFirebaseAuth.currentUser).thenReturn(mockUser);
        expect(authService.currentUsr, mockUser);
        when(mockFirebaseAuth.currentUser).thenReturn(null);
        expect(authService.currentUsr, isNull);
      });
    });

    group('authStateChanges stream (user)', () {
      test('should correctly map fb_auth.User to UserHandler', () async {
        final controller = StreamController<fb_auth.User?>();
        when(mockFirebaseAuth.authStateChanges()).thenAnswer((_) => controller.stream);

        // Re-initialize authService to use the new stream mock
        authService = AuthService.test(mockFirebaseAuth, mockGoogleSignIn, mockDatabaseService);

        final expectation = expectLater(
          authService.user,
          emitsInOrder([
            isA<UserHandler>()
              .having((uh) => uh.uid, 'uid', 'stream_user_uid')
              .having((uh) => uh.email, 'email', 'stream@example.com'),
            // Add more expected UserHandler objects or null for sign-out
          ]),
        );

        final mockStreamUser = MockUser();
        when(mockStreamUser.uid).thenReturn('stream_user_uid');
        when(mockStreamUser.email).thenReturn('stream@example.com');
        controller.add(mockStreamUser);

        await controller.close(); // Close the stream to complete the emitsInOrder matcher
        await expectation;
      });

       test('emits UserHandler with empty userType from _userFromFirebaseUser', () {
        // Directly testing the mapping function's typical output via the stream
        final mockFbUser = MockUser();
        when(mockFbUser.uid).thenReturn('uid123');
        when(mockFbUser.email).thenReturn('email123@example.com');

        // This is an indirect way to test _userFromFirebaseUser
        final userHandler = authService.testUserFromFirebaseUser(mockFbUser);
        expect(userHandler.uid, 'uid123');
        expect(userHandler.email, 'email123@example.com');
        expect(userHandler.userType, ''); // As per current implementation
      });
    });
  });
}

// Helper extension or modification in AuthService is needed for:
// - AuthService.test(mockFirebaseAuth, mockGoogleSignIn, mockDatabaseService)
// - authService.testUserFromFirebaseUser(mockFbUser)
// This will be done in the next step when refactoring AuthService.
