import '../models/module_model.dart';

const modulesMap = {
  "formations": {
    "python": [
      "session_01",
      "session_02",
      "session_03",
      "session_04",
      "session_05",
      "session_06",
      "session_07",
      "session_08",
      "session_09",
      "session_10",
    ]
  },
  "Sem 9": {
    "iriia": [
      "Academic Ethics & Deontology",
      "Advanced Artificial Intelligence (Deep Learning)",
      "Home Automation for Renewable Energy",
      "Industrial Metrology",
      "Mobile Applications & HMI under Android",
      "N-tier Development",
      "Smart Grids",
      "Virualization & Industrial Control on the Cloud",
      "Workshop: Entrepreneurship & Startup Establishment",
    ],
    "er": [
      "Electrical Energy Quality",
      "Energy Audit",
      "Energy Transition & Legislation &amp; Regulation",
      "Innovation, Intellectual Property & Ethics",
      "Microgrids & Smart Grids",
      "Monitoring, Diagnosis & Maintenance of Energy Systems",
      "Project Management & Life Cycle Analysis",
      "Techno-economic Optimisation of Hybrid Systems",
      "Technological Trends",
      "Workshop 1: Entrepreneurship & Startup Establishment",
      "Workshop 2 : Engineering Project Study",
    ],
    "micro": [""],
    "ge": [""],
    "gh": [""],
  },
  "Sem 7": {
    "iriia": [
      "Human-Machine Interaction for Industry",
      "Industrial Local Area Networks",
      "Industrial Programmable Logic Controllers",
      "Machine Learning",
      "Programming networks & web services",
      "µ-Controllers 2",
    ],
    "er": [
      "Building Energy",
      "Design & Optimisation of PV Power Plants",
      "Design & Optimization of Wind Power Plants",
      "Energy Storage",
      "Green hydrogen supply chains",
      "Modelling & Optimisation of Energy Systems",
    ],
    "micro": [
      "Integrated circuit design 1",
      "Photovoltaic devices",
      "Electronic functions 1",
      "µ-Controllers 2",
      "Legal metrology",
      "Simulation tools",
      "Digital signal processing",
    ],
    "ge": [
      "Control of Electrical Drives",
      "Power Electronics 2",
      "Modelling of Electric Actuators",
      "Mircoprocessor microcontrollers",
      "Legal metrology",
      "Smart grids",
      "Computer tools 2 for engineers",
      "Electrical energy production and storage",
      "Electric power systems",
      "Artificial intelligence techniques",
    ],
    "gh": [""],
  },
  "Sem 5": {
    "iriia": [
      "Computer Networks 1",
      "Computer Architecture",
      "Operating systems",
      "Renewable Energy & Energy Efficiency",
      "Sensors & Actuators",
    ],
    "er": [
      "Electrical Machines",
      "Fluid mechanics",
      "Renewable Energy Resources",
      "Scientific computing & programming",
      "Applied Thermodynamics",
      "Workshop 1",
    ],
    "micro": [
      "Circuit theory",
      "Combinational & Sequential Logic",
      "Maths Complex analysis",
      "Renewable Energy",
      "Semiconductor Physics 1",
      "Signal Theory",
      "3rd micro modules 7",
      "3rd micro modules 8",
      "3rd micro modules 9",
    ],
    "ge": [
      "Basic Linear Control Systems",
      "Electronique Analogique",
      "Electromagnetism & waves",
      "Fundamental Electrotechnics",
      "Mathematics for engineers",
      "Sensors & measuring instruments",
      "Signal processing",
    ],
    "gh": [""],
  }
};

const Map<String, List<String>> specialities = {
  /* 'Sem 1': ['er', 'ge', 'gh', 'iriia', 'micro'],
  'Sem 2': ['er', 'ge', 'gh', 'iriia', 'micro'],
  'Sem 3': ['er', 'ge', 'gh', 'iriia', 'micro'],
  'Sem 4': ['er', 'ge', 'gh', 'iriia', 'micro'], */
  'Sem 5': ['er', 'ge', 'gh', 'iriia', 'micro'],
  'Sem 7': ['er', 'ge', 'gh', 'iriia', 'micro'],
  'Sem 9': ['er', 'ge', 'gh', 'iriia', 'micro'],
  'formations': ['python'],
};

// Inserting random list of module data
List<Module> randomModuleData = [
  Module(
    uid: "randomUid1",
    name: "Random Module 1",
    isActive: false,
    speciality: "randomSpeciality1",
    grade: "randomGrade1",
    numberOfStudents: 14,
    students: {
      "student1": "name std 1",
      "student2": "name std 2",
      "student3": "name std 3",
      "student4": "name std 4",
      "student5": "name std 5",
      "student6": "name std 6",
      "student7": "name std 7",
      "student8": "name std 8",
      "student9": "name std 9",
      "student10": "name std 10",
      "student11": "name std 11",
      "student12": "name std 12",
      "student13": "name std 13",
      "student14": "name std 14",
    },
    attendanceTable: {
      "16-01-2023": {
        "student1": true,
        "student2": false,
        "student3": true,
        "student4": true,
        "student5": true,
        "student6": false,
        "student7": true,
        "student8": true,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": false,
        "student13": true,
        "student14": false,
      },
      "17-01-2023": {
        "student1": true,
        "student2": true,
        "student3": true,
        "student4": true,
        "student5": true,
        "student6": false,
        "student7": true,
        "student8": false,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": false,
        "student13": true,
        "student14": false,
      },
      "18-01-2023": {
        "student1": false,
        "student2": false,
        "student3": true,
        "student4": true,
        "student5": true,
        "student6": false,
        "student7": false,
        "student8": false,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": true,
        "student13": true,
        "student14": true,
      },
      "19-01-2023": {
        "student1": true,
        "student2": true,
        "student3": true,
        "student4": true,
        "student5": true,
        "student6": true,
        "student7": true,
        "student8": true,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": true,
        "student13": true,
        "student14": true,
      },
    },
  ),
  Module(
    uid: "randomUid2",
    name: "Random Module 2",
    isActive: false,
    speciality: "randomSpeciality2",
    grade: "randomGrade2",
    numberOfStudents: 14,
    students: {
      "student1": "name std 1",
      "student2": "name std 2",
      "student3": "name std 3",
      "student4": "name std 4",
      "student5": "name std 5",
      "student6": "name std 6",
      "student7": "name std 7",
      "student8": "name std 8",
      "student9": "name std 9",
      "student10": "name std 10",
      "student11": "name std 11",
      "student12": "name std 12",
      "student13": "name std 13",
      "student14": "name std 14",
    }, // 41
    attendanceTable: {
      "16-01-2023": {
        "student1": false,
        "student2": false,
        "student3": true,
        "student4": true,
        "student5": true,
        "student6": false,
        "student7": true,
        "student8": false,
        "student9": false,
        "student10": false,
        "student11": true,
        "student12": false,
        "student13": true,
        "student14": false,
      },
      "17-01-2023": {
        "student1": true,
        "student2": true,
        "student3": true,
        "student4": false,
        "student5": true,
        "student6": false,
        "student7": true,
        "student8": false,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": false,
        "student13": false,
        "student14": false,
      },
      "18-01-2023": {
        "student1": false,
        "student2": true,
        "student3": true,
        "student4": true,
        "student5": true,
        "student6": false,
        "student7": true,
        "student8": true,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": true,
        "student13": true,
        "student14": true,
      },
      "19-01-2023": {
        "student1": true,
        "student2": true,
        "student3": true,
        "student4": false,
        "student5": true,
        "student6": true,
        "student7": true,
        "student8": false,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": true,
        "student13": false,
        "student14": true,
      },
    }, //37
  ),
  Module(
    uid: "randomUid3",
    name: "Random Module 3",
    isActive: false,
    speciality: "randomSpeciality3",
    grade: "randomGrade3",
    numberOfStudents: 14,
    students: {
      "student1": "name std 1",
      "student2": "name std 2",
      "student3": "name std 3",
      "student4": "name std 4",
      "student5": "name std 5",
      "student6": "name std 6",
      "student7": "name std 7",
      "student8": "name std 8",
      "student9": "name std 9",
      "student10": "name std 10",
      "student11": "name std 11",
      "student12": "name std 12",
      "student13": "name std 13",
      "student14": "name std 14",
    },
    attendanceTable: {
      "16-01-2023": {
        "student1": true,
        "student2": false,
        "student3": true,
        "student4": true,
        "student5": true,
        "student6": true,
        "student7": true,
        "student8": true,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": true,
        "student13": true,
        "student14": true,
      },
      "17-01-2023": {
        "student1": true,
        "student2": true,
        "student3": true,
        "student4": true,
        "student5": true,
        "student6": false,
        "student7": true,
        "student8": true,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": true,
        "student13": true,
        "student14": false,
      },
      "18-01-2023": {
        "student1": false,
        "student2": false,
        "student3": true,
        "student4": true,
        "student5": true,
        "student6": false,
        "student7": false,
        "student8": false,
        "student9": true,
        "student10": true,
        "student11": false,
        "student12": true,
        "student13": true,
        "student14": false,
      },
      "19-01-2023": {
        "student1": true,
        "student2": true,
        "student3": false,
        "student4": false,
        "student5": false,
        "student6": true,
        "student7": true,
        "student8": true,
        "student9": true,
        "student10": true,
        "student11": false,
        "student12": false,
        "student13": true,
        "student14": true,
      },
    }, //41
  ),
  Module(
    uid: "randomUid4",
    name: "Random Module 4",
    isActive: false,
    speciality: "randomSpeciality4",
    grade: "randomGrade4",
    numberOfStudents: 14,
    students: {
      "student1": "name std 1",
      "student2": "name std 2",
      "student3": "name std 3",
      "student4": "name std 4",
      "student5": "name std 5",
      "student6": "name std 6",
      "student7": "name std 7",
      "student8": "name std 8",
      "student9": "name std 9",
      "student10": "name std 10",
      "student11": "name std 11",
      "student12": "name std 12",
      "student13": "name std 13",
      "student14": "name std 14",
    },
    attendanceTable: {
      "16-01-2023": {
        "student1": true,
        "student2": true,
        "student3": false,
        "student4": false,
        "student5": true,
        "student6": true,
        "student7": true,
        "student8": true,
        "student9": true,
        "student10": true,
        "student11": true,
        "student12": false,
        "student13": true,
        "student14": false,
      },
      "17-01-2023": {
        "student1": true,
        "student2": true,
        "student3": true,
        "student4": false,
        "student5": true,
        "student6": false,
        "student7": true,
        "student8": true,
        "student9": true,
        "student10": true,
        "student11": false,
        "student12": true,
        "student13": true,
        "student14": true,
      },
      "18-01-2023": {
        "student1": true,
        "student2": true,
        "student3": true,
        "student4": false,
        "student5": false,
        "student6": false,
        "student7": true,
        "student8": true,
        "student9": true,
        "student10": true,
        "student11": false,
        "student12": false,
        "student13": true,
        "student14": true,
      },
      "19-01-2023": {
        "student1": true,
        "student2": true,
        "student3": false,
        "student4": false,
        "student5": true,
        "student6": true,
        "student7": true,
        "student8": true,
        "student9": false,
        "student10": false,
        "student11": false,
        "student12": true,
        "student13": true,
        "student14": true,
      },
    },
  ),
];
